CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS SOCIAL_ACTIONS;

CREATE TABLE IF NOT EXISTS SOCIAL_ACTIONS.SOCIAL_ACTIONS (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP,
    completed_at TIMESTAMP
);