CREATE SCHEMA IF NOT EXISTS SOCIAL_ACTIONS;

CREATE TABLE IF NOT EXISTS SOCIAL_ACTIONS.SOCIAL_ACTIONS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE SEQUENCE IF NOT EXISTS SOCIAL_ACTIONS_SEQ;