name: CI workflow
on:
  pull_request:
    branches:
      - 'main'
      
  push:
    branches: 
      - '**' 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Maven clean install
        run: mvn clean install

      - name: Tests
        run: mvn --batch-mode --update-snapshots verify
