name: CI workflow
on:
  pull_request:
    branches:
      - 'main'
      
  push:
    branches: 
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: SETUP JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: INSTALL DEPENDENCIES
        run: mvn install

      - name: TEST
        run: mvn --batch-mode --update-snapshots verify
